# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    resource_class: "small"
    docker:
      - image: schickling/latex:latest
    steps:
      - checkout
      - run: pdflatex CV
      - store_artifacts:
          path: CV.pdf
      - persist_to_workspace:
          root: '.'
          paths:
            - "CV.pdf"
  release:
    resource_class: "small"
    docker:
      - image: circleci/golang:1.14.0
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: "Get Current Time"
          command: |
            echo 'export RELEASE_TAG_NAME=`date +"%Y.%m.%d"`' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: "Get Libraries"
          command: go get github.com/aktau/github-release github.com/tcnksm/ghr
      - run:
          name: "Delete release if it exists"
          command: |
            set +e
            github-release delete -s $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -t $RELEASE_TAG_NAME
            true
      - run:
          name: "Make a release"
          command: ghr --token $GITHUB_TOKEN --username $CIRCLE_PROJECT_USERNAME --repository $CIRCLE_PROJECT_REPONAME --name $RELEASE_TAG_NAME --body "Update" $RELEASE_TAG_NAME CV.pdf

workflows:
  build_and_release:
    jobs:
      - build
      - release:
          context: GithubRepoAccess
          requires:
            - build